/* Autogenerated with DRAKON Editor 1.15 */
#include "6502.h"

#include "PLA.h"

#define PHI1    (cpu->PHI1)
#define PHI2    (cpu->PHI2)

// Basic logic
#define BIT(n)     ( (n) & 1 )
int NOT(int a) { return (~a & 1); }
int NAND(int a, int b) { return ~((a & 1) & (b & 1)) & 1; }
int NOR(int a, int b) { return ~((a & 1) | (b & 1)) & 1; }

// Bottom-part controls
int ADH_ABH, ADL_ABL, Y_SB, X_SB, ZERO_ADL0, ZERO_ADL1, ZERO_ADL2,
    SB_Y, SB_X, S_SB, S_ADL, SB_S, S_S, nDB_ADD, DB_ADD,
    ZERO_ADD, SB_ADD, ADL_ADD, ANDS, EORS, ORS, I_ADDC, SRS, SUMS, nDAA,
    ADD_SB7, ADD_SB06, ADD_ADL, nDSA, AVR, ACR, ZERO_ADH0, SB_DB, SB_AC,
    SB_ADH, ZERO_ADH17, AC_SB, AC_DB, ADH_PCH, PCH_PCH, PCH_DB, PCL_DB,
    PCH_ADH, PCL_PCL, PCL_ADL, ADL_PCL, IPC, DL_ADL, DL_ADH, DL_DB;

// Top part context

int nNMI, nIRQ, RES;
int RDY, PREVRDY;
static char PREVRDY_Latch[2];
int SO;

static unsigned char char T, IR, PD;
char PLA[129];   // 129 active lines.
int TWOCYCLE, IMPLIED;

// Bottom part context




static void ACR_LATCH(void);

static void AC_SB(void);

static void ADDRESS_BUS(
    Context6502 * cpu
);

static void ADD_SB7(void);

static void ADH_ABH(void);

static void ADL_ABL(void);

static void ALU(
    Context6502 * cpu
);

static void ALU_SETUP(void);

static void ANDS(void);

static void BOTTOM_PART(
    Context6502 *cpu
);

static void BRANCH_BACK(void);

static void BRANCH_LOGIC(void);

static void B_FLAG(void);

static void CLOCK(
    Context6502 *cpu
);

static void C_FLAG(void);

static void DAA_DSA(void);

static void DECODER(
    Context6502 * cpu
);

static void DL_ADH(void);

static void DL_ADL(void);

static void DL_DB(void);

static void D_FLAG(void);

static void ENDS(void);

static void ENDX(void);

static void EXEC_CTRL(void);

static void FETCH(void);

static void FLAG_CTRL(void);

static void FLAG_IO(void);

static void IND(void);

static void INSTR_REG(void);

static void INTR_ADDR(void);

static void IPC(void);

static void IRQ_PAD(void);

static void IRQ_SELECT(void);

static void I_FLAG(void);

static void MEMOP(void);

static void NMI_PAD(
    Context6502 * cpu
);

static void NOADL(void);

static void N_FLAG(void);

static void PC_SETUP(void);

static void PREDECODE(
    Context6502 * cpu
);

static void PROGRAM_COUNTER(
    Context6502 * cpu
);

static void RANDOM_LOGIC(void);

static void RDY_PAD(
    Context6502 * cpu
);

static void READY_CTRL(void);

static void REGS(
    Context6502 * cpu
);

static void RES_PAD(
    Context6502 * cpu
);

static void RW_SELECT(void);

static void SB_AC(void);

static void SB_ADH(void);

static void SB_DB(void);

static void SB_XY(void);

static void SO_PAD(void);

static void SREG_CTRL(void);

static void SRS(void);

static void STOR(void);

static void T0_T1(void);

static void T2_T5(void);

static void T5_T6(void);

static void TOP_PART(
    Context6502 *cpu
);

static void T_CTRL(void);

static void V_FLAG(void);

static void WR_DL(void);

static void XY_SB(void);

static void ZERO_ADH0(void);

static void ZERO_ADH17(void);

static void Z_FLAG(void);

static void ACR_LATCH(void) {
}

static void AC_SB(void) {
}

static void ADDRESS_BUS(
    Context6502 * cpu
) {
    // item 172
    if (PHI1) {
        /* item 175 */
        ADL &= ~ ((ZERO_ADL2 << 2) | (ZERO_ADL1 << 1) | (ZERO_ADL0 << 0));
        if (ZERO_ADH0) ADH &= ~0x01;
        if (ZERO_ADH17) ADH &= ~0xFE;
        if (ADH_ABH) ABH = ADH;
        if (ADL_ABL) ABL = ADL;
        return;
    } else {
        return;
    }
    
}

static void ADD_SB7(void) {
}

static void ADH_ABH(void) {
}

static void ADL_ABL(void) {
}

static void ALU(
    Context6502 * cpu
) {
}

static void ALU_SETUP(void) {
}

static void ANDS(void) {
}

static void BOTTOM_PART(
    Context6502 *cpu
) {
    // item 311
    if (PHI2) {
        /* item 314 */
        // precharge internal buses
        SB = DB = ADH = ADL = 0xff;
        return;
    } else {
        return;
    }
    
}

static void BRANCH_BACK(void) {
}

static void BRANCH_LOGIC(void) {
}

static void B_FLAG(void) {
}

static void CLOCK(
    Context6502 *cpu
) {
    // item 104
    PHI1 = NOT(cpu->PHI0);
    PHI2 = cpu->PHI0;
    return;
    
}

static void C_FLAG(void) {
}

static void DAA_DSA(void) {
}

static void DECODER(
    Context6502 * cpu
) {
}

static void DL_ADH(void) {
}

static void DL_ADL(void) {
}

static void DL_DB(void) {
}

static void D_FLAG(void) {
}

static void ENDS(void) {
}

static void ENDX(void) {
}

static void EXEC_CTRL(void) {
}

static void FETCH(void) {
}

static void FLAG_CTRL(void) {
}

static void FLAG_IO(void) {
}

static void IND(void) {
}

static void INSTR_REG(void) {
}

static void INTR_ADDR(void) {
}

static void IPC(void) {
}

static void IRQ_PAD(void) {
    // item 542
    nIRQ = 1;
    return;
    
}

static void IRQ_SELECT(void) {
}

static void I_FLAG(void) {
}

static void MEMOP(void) {
}

static void NMI_PAD(
    Context6502 * cpu
) {
    // item 541
    nNMI = 1;
    return;
    
}

static void NOADL(void) {
}

static void N_FLAG(void) {
}

static void PC_SETUP(void) {
}

static void PREDECODE(
    Context6502 * cpu
) {
    // item 309
    int p[4];
    
    #define PD(n)   ((PD >> n) & 1)
    #define nPD(n)  (NOT((PD >> n) & 1))
    
    // item 305
    if (PHI2) {
        /* item 308 */
        PD = cpu->DATA;
    } else {
    }
    
    // item 310
    // Determine whenever instruction takes 2 cycle / implied.
    p[0] = NOT ( PD(2) | nPD(3) | PD(4) | nPD(0) );     // XXX010X1
    p[1] = NOT ( PD(2) | nPD(3) | PD(0) );      // XXXX10X0
    p[2] = NOT ( PD(4) | PD(7) | PD(1) );       // 0XX0XX0X
    p[3] = NOT ( PD(2) | PD(3) | PD(4) | nPD(7) | PD(0) );  // 1XX000X0
    TWOCYCLE = p[0] | p[3] | (NOT(p[2]) & p[1]);
    IMPLIED = p[1];
    return;
    
}

static void PROGRAM_COUNTER(
    Context6502 * cpu
) {
}

static void RANDOM_LOGIC(void) {
}

static void RDY_PAD(
    Context6502 * cpu
) {
    // item 544
    RDY = cpu->RDY;
    
    // item 545
    if (PHI2) {
        /* item 548 */
        PREVRDY_Latch[0] = NOT(cpu->RDY);
    } else {
    }
    
    // item 549
    if (PHI1) {
        /* item 552 */
        PREVRDY_Latch[1] = NOT(PREVRDY_Latch[0]);
    } else {
    }
    
    // item 553
    PREVRDY = NOT (PREVRDY_Latch[1]);
    return;
    
}

static void READY_CTRL(void) {
}

static void REGS(
    Context6502 * cpu
) {
    // item 160
    if (PHI1) {
        /* item 163 */
        if (X_SB) SB = X;
        else if (SB_X) X = SB;
        if (Y_SB) SB = Y;
        else if (SB_Y) Y = SB;
        if (SB_S) S = SB;
        else if (S_SB) SB = S;
        if (S_ADL) ADL = S;
        return;
    } else {
        return;
    }
    
}

static void RES_PAD(
    Context6502 * cpu
) {
    // item 543
    RES = 1;
    return;
    
}

static void RW_SELECT(void) {
}

static void SB_AC(void) {
}

static void SB_ADH(void) {
}

static void SB_DB(void) {
}

static void SB_XY(void) {
}

static void SO_PAD(void) {
    // item 554
    SO = 0;
    return;
    
}

static void SREG_CTRL(void) {
}

static void SRS(void) {
}

static void STOR(void) {
}

static void T0_T1(void) {
}

static void T2_T5(void) {
}

static void T5_T6(void) {
}

static void TOP_PART(
    Context6502 *cpu
) {
    // item 197
    CLOCK (cpu);
    /* item 198 */
    NMI_PAD (cpu);
    /* item 199 */
    IRQ_PAD (cpu);
    /* item 200 */
    RES_PAD (cpu);
    /* item 540 */
    SO_PAD (cpu);
    /* item 555 */
    RDY_PAD (cpu);
    /* item 559 */
    DECODER (cpu);
    /* item 615 */
    READY_CTRL (cpu);
    /* item 581 */
    IRQ_SELECT (cpu);
    /* item 582 */
    INTR_ADDR (cpu);
    /* item 608 */
    ACR_LATCH (cpu);
    /* item 566 */
    I_FLAG (cpu);
    /* item 567 */
    C_FLAG (cpu);
    /* item 568 */
    D_FLAG (cpu);
    /* item 569 */
    V_FLAG (cpu);
    /* item 570 */
    N_FLAG (cpu);
    /* item 583 */
    B_FLAG (cpu);
    /* item 576 */
    BRANCH_BACK (cpu);
    /* item 577 */
    BRANCH_LOGIC (cpu);
    /* item 668 */
    ANDS (cpu);
    /* item 669 */
    SRS (cpu);
    /* item 675 */
    NOADL (cpu);
    /* item 676 */
    IND (cpu);
    /* item 687 */
    MEMOP (cpu);
    /* item 693 */
    STOR (cpu);
    /* item 657 */
    DAA_DSA (cpu);
    /* item 645 */
    ADL_ABL (cpu);
    /* item 649 */
    SB_ADH (cpu);
    /* item 653 */
    ADH_ABH (cpu);
    /* item 637 */
    SB_AC (cpu);
    /* item 641 */
    AC_SB (cpu);
    /* item 632 */
    FLAG_CTRL (cpu);
    /* item 633 */
    FLAG_IO (cpu);
    /* item 619 */
    RW_SELECT (cpu);
    /* item 628 */
    IPC (cpu);
    /* item 603 */
    ENDS (cpu);
    /* item 604 */
    ENDX (cpu);
    /* item 599 */
    EXEC_CTRL (cpu);
    /* item 609 */
    T0_T1 (cpu);
    /* item 610 */
    T2_T5 (cpu);
    /* item 611 */
    T5_T6 (cpu);
    /* item 588 */
    FETCH (cpu);
    /* item 593 */
    PREDECODE (cpu);
    /* item 595 */
    INSTR_REG (cpu);
    return;
    
}

static void T_CTRL(void) {
}

static void V_FLAG(void) {
}

static void WR_DL(void) {
}

static void XY_SB(void) {
}

static void ZERO_ADH0(void) {
}

static void ZERO_ADH17(void) {
}

static void Z_FLAG(void) {
}

void Step6502(
    Context6502 *cpu
) {
    // item 77
    TOP_PART (cpu);
    /* item 78 */
    BOTTOM_PART (cpu);
    return;
    
}



