/* Autogenerated with DRAKON Editor 1.15 */
#ifndef 6502_H40134
#define 6502_H40134

typedef struct Context6502 {
    char nNMI;
    char nIRQ;
    char PHI1;
    char RDY;
    char nRES;
    char PHI2;
    char SO;
    char PHI0;
    char RW;
    unsigned char DATA;
    unsigned short ADDR;
    char SYNC;
} Context6502;


void Step6502(
    Context6502 *cpu
);


#endif

