
// PLA line names

// Group A

#define PLA_STY             (cpu->PLAOUT[0])
#define PLA_IND_Y           (cpu->PLAOUT[1])
#define PLA_ABS_Y           (cpu->PLAOUT[2])
#define PLA_3               (cpu->PLAOUT[3])
#define PLA_4               (cpu->PLAOUT[4])
#define PLA_5               (cpu->PLAOUT[5])

// Group B

#define PLA_6               (cpu->PLAOUT[6])
#define PLA_7               (cpu->PLAOUT[7])
#define PLA_8               (cpu->PLAOUT[8])
#define PLA_9               (cpu->PLAOUT[9])
#define PLA_10              (cpu->PLAOUT[10])
#define PLA_11              (cpu->PLAOUT[11])
#define PLA_PUTX            (cpu->PLAOUT[12])
#define PLA_TXS             (cpu->PLAOUT[13])
#define PLA_14              (cpu->PLAOUT[14])
#define PLA_15              (cpu->PLAOUT[15])
#define PLA_16              (cpu->PLAOUT[16])
#define PLA_17              (cpu->PLAOUT[17])
#define PLA_18              (cpu->PLAOUT[18])
#define PLA_19              (cpu->PLAOUT[19])
#define PLA_20              (cpu->PLAOUT[20])

// Group C

#define PLA_21              (cpu->PLAOUT[21])
#define PLA_22              (cpu->PLAOUT[22])
#define PLA_23              (cpu->PLAOUT[23])
#define PLA_24              (cpu->PLAOUT[24])
#define PLA_25              (cpu->PLAOUT[25])
#define PLA_26              (cpu->PLAOUT[26])
#define PLA_27              (cpu->PLAOUT[27])
#define PLA_28              (cpu->PLAOUT[28])
#define PLA_29              (cpu->PLAOUT[29])
#define PLA_30              (cpu->PLAOUT[30])
#define PLA_31              (cpu->PLAOUT[31])
#define PLA_32              (cpu->PLAOUT[32])
#define PLA_33              (cpu->PLAOUT[33])
#define PLA_34              (cpu->PLAOUT[34])
#define PLA_35              (cpu->PLAOUT[35])
#define PLA_36              (cpu->PLAOUT[36])

// Group D

#define PLA_37              (cpu->PLAOUT[37])
#define PLA_38              (cpu->PLAOUT[38])
#define PLA_39              (cpu->PLAOUT[39])
#define PLA_40              (cpu->PLAOUT[40])
#define PLA_41              (cpu->PLAOUT[41])
#define PLA_42              (cpu->PLAOUT[42])
#define PLA_43              (cpu->PLAOUT[43])
#define PLA_44              (cpu->PLAOUT[44])
#define PLA_45              (cpu->PLAOUT[45])
#define PLA_46              (cpu->PLAOUT[46])
#define PLA_47              (cpu->PLAOUT[47])
#define PLA_48              (cpu->PLAOUT[48])
#define PLA_49              (cpu->PLAOUT[49])
#define PLA_50              (cpu->PLAOUT[50])
#define PLA_51              (cpu->PLAOUT[51])
#define PLA_52              (cpu->PLAOUT[52])
#define PLA_53              (cpu->PLAOUT[53])

// Group E

#define PLA_54              (cpu->PLAOUT[54])
#define PLA_55              (cpu->PLAOUT[55])
#define PLA_56              (cpu->PLAOUT[56])
#define PLA_57              (cpu->PLAOUT[57])
#define PLA_58              (cpu->PLAOUT[58])
#define PLA_59              (cpu->PLAOUT[59])
#define PLA_60              (cpu->PLAOUT[60])
#define PLA_61              (cpu->PLAOUT[61])
#define PLA_62              (cpu->PLAOUT[62])
#define PLA_63              (cpu->PLAOUT[63])
#define PLA_64              (cpu->PLAOUT[64])
#define PLA_65              (cpu->PLAOUT[65])
#define PLA_66              (cpu->PLAOUT[66])
#define PLA_67              (cpu->PLAOUT[67])
#define PLA_68              (cpu->PLAOUT[68])
#define PLA_69              (cpu->PLAOUT[69])
#define PLA_70              (cpu->PLAOUT[70])
#define PLA_71              (cpu->PLAOUT[71])
#define PLA_72              (cpu->PLAOUT[72])

// Group F

#define PLA_73              (cpu->PLAOUT[73])
#define PLA_74              (cpu->PLAOUT[74])
#define PLA_75              (cpu->PLAOUT[75])
#define PLA_76              (cpu->PLAOUT[76])
#define PLA_77              (cpu->PLAOUT[77])
#define PLA_78              (cpu->PLAOUT[78])
#define PLA_79              (cpu->PLAOUT[79])
#define PLA_80              (cpu->PLAOUT[80])
#define PLA_81              (cpu->PLAOUT[81])
#define PLA_82              (cpu->PLAOUT[82])
#define PLA_83              (cpu->PLAOUT[83])
#define PLA_84              (cpu->PLAOUT[84])
#define PLA_85              (cpu->PLAOUT[85])
#define PLA_86              (cpu->PLAOUT[86])
#define PLA_87              (cpu->PLAOUT[87])
#define PLA_88              (cpu->PLAOUT[88])
#define PLA_89              (cpu->PLAOUT[89])
#define PLA_90              (cpu->PLAOUT[90])

// Group G

#define PLA_91              (cpu->PLAOUT[91])
#define PLA_92              (cpu->PLAOUT[92])
#define PLA_93              (cpu->PLAOUT[93])
#define PLA_94              (cpu->PLAOUT[94])
#define PLA_95              (cpu->PLAOUT[95])
#define PLA_96              (cpu->PLAOUT[96])
#define PLA_STORE           (cpu->PLAOUT[97])
#define PLA_98              (cpu->PLAOUT[98])
#define PLA_99              (cpu->PLAOUT[99])
#define PLA_100             (cpu->PLAOUT[100])
#define PLA_101             (cpu->PLAOUT[101])
#define PLA_102             (cpu->PLAOUT[102])
#define PLA_103             (cpu->PLAOUT[103])

// Group H

#define PLA_104             (cpu->PLAOUT[104])
#define PLA_105             (cpu->PLAOUT[105])
#define PLA_106             (cpu->PLAOUT[106])
#define PLA_107             (cpu->PLAOUT[107])
#define PLA_108             (cpu->PLAOUT[108])
#define PLA_109             (cpu->PLAOUT[109])
#define PLA_110             (cpu->PLAOUT[110])
#define PLA_MEM_ZPXY        (cpu->PLAOUT[111])
#define PLA_112             (cpu->PLAOUT[112])
#define PLA_113             (cpu->PLAOUT[113])
#define PLA_114             (cpu->PLAOUT[114])
#define PLA_115             (cpu->PLAOUT[115])
#define PLA_116             (cpu->PLAOUT[116])
#define PLA_117             (cpu->PLAOUT[117])
#define PLA_118             (cpu->PLAOUT[118])
#define PLA_119             (cpu->PLAOUT[119])

// Group K

#define PLA_120             (cpu->PLAOUT[120])
#define PLA_121             (cpu->PLAOUT[121])
#define PLA_MEM_ABS         (cpu->PLAOUT[122])
#define PLA_MEM_ZP          (cpu->PLAOUT[123])
#define PLA_MEM_IND         (cpu->PLAOUT[124])
#define PLA_MEM_ABSXY       (cpu->PLAOUT[125])
#define PLA_126             (cpu->PLAOUT[126])
#define PLA_127             (cpu->PLAOUT[127])
#define PLA_128             (cpu->PLAOUT[128])

void DecodePLA (Context6502 * cpu);
